version: '3.8'

volumes:
  static_volume:
  postgres_data:
  media_volume:

services:
  db:
    image: postgres:13.0
    container_name: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: thezavitaev/foodgram:latest
    container_name: foodgram
    restart: always
    volumes:
      - ./static_volume:/code/static/
      - ./media_volume:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.4
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./static_volume:/code/static/
      - ./media_volume:/code/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web