version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13.0
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: thezavitaev/foodgram:latest
    restart: always
    volumes:
      - ./static:/code/static
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.4
    restart: unless-stopped
    volumes:
      - ./static:/code/static
      - ./media:/code/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web