# Generated by Django 3.1.4 on 2020-12-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201128_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serving',
            field=models.PositiveSmallIntegerField(default=1, help_text='в штуках', verbose_name='Количество порций'),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество ингредиентов'),
        ),
    ]
