# Generated by Django 3.1.4 on 2020-12-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20201208_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure',
            new_name='dimension',
        ),
    ]
