# Generated by Django 3.1.4 on 2020-12-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20201211_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favourite',
        ),
    ]
