# Generated by Django 3.1.4 on 2020-12-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20201213_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientvalue',
            options={'verbose_name': 'Количество ингридиентов', 'verbose_name_plural': 'Количество ингридиентов'},
        ),
    ]
