# Generated by Django 3.1.4 on 2020-12-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20201216_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='recipes',
        ),
        migrations.AddField(
            model_name='purchase',
            name='recipes',
            field=models.ManyToManyField(to='recipes.Recipe', verbose_name='Список рецептов'),
        ),
    ]
