# Generated by Django 3.1.4 on 2020-12-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20201216_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientvalue',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_values', to='recipes.recipe'),
        ),
    ]
